---
title: "Join addresses to details"
output: 
  html_document: 
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
```

# Load required packages

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(lubridate)
library(here)
```

# Import and clean data

```{r}
# import data
addresses <- read.csv(here::here("data", "Master_Address_Table.csv")) %>% 
  as_tibble() %>% 
  mutate_if(is.factor, as.character)

resdetails <- read_csv(here::here("data", "Real_Estate_Residential_Details.csv"))

comdetails <- read_csv(here::here("data", "Real_Estate_Commercial_Details.csv"))

resjoined <- addresses %>% 
  inner_join(resdetails, by=c("OBJECTID"="RecordID_Int")) %>% 
  clean_names() %>% 
  na_if(" ") %>% 
  na_if("") %>% 
  remove_empty(c("rows", "cols"))

comjoined <- addresses %>% 
  inner_join(comdetails, by=c("OBJECTID"="RecordID_Int")) %>% 
  clean_names() %>% 
  na_if(" ") %>% 
  na_if("") %>% 
  remove_empty(c("rows", "cols"))

```

Take a look at the joined **residential** data:

```{r, echo=FALSE}
resjoined
```

Take a look at the joined **commercial** data:

```{r, echo=FALSE}
resjoined
```

Geocode the commercial data:

```{r}
library(ggmap)
comjoined <- comjoined %>% 
  mutate(address=paste(st_number, st_name, suffix, "Charlottesville VA", zip)) %>% 
  select(objectid, address) %>% 
  distinct() %>% 
  mutate(latlon=list(geocode(address)))
```

Write out cleaned data

```{r}
resjoined %>% write_csv(here::here("data", "addresses-joined-to-details-residential.csv"))
comjoined %>% write_csv(here::here("data", "addresses-joined-to-details-commercial.csv"))
```

